package loadout

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/justinrush/q/internal/domain"
)

// ShellQuote wraps a string in single quotes for POSIX sh, escaping any it
// contains.
//
// Prompts routinely contain quotes, backticks, dollar signs, and newlines, all of
// which a shell would otherwise interpret, so this is applied to every generated
// value without exception.
func ShellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// LaunchSpec describes the agent invocation to generate a script for.
type LaunchSpec struct {
	// Tool selects the agent.
	Tool domain.Tool
	// Bin is the absolute path to the agent binary.
	Bin string
	// MissionDir is the agent's working directory.
	MissionDir string
	// MissionID and HookEpoch identify the mission to its hooks.
	MissionID domain.MissionID
	HookEpoch int
	// DaemonFile is the path to the daemon handle.
	DaemonFile string
	// SessionID is the agent session to use or resume. For claude this is chosen
	// in advance; for codex it is only known after the session has started, so it
	// is empty on a first launch.
	SessionID string
	// Resume continues SessionID rather than starting fresh.
	Resume bool
	// PlanMode starts claude in plan mode.
	PlanMode bool
	// DisplayName is shown in the agent's own UI.
	DisplayName string
	// Worktrees are the absolute worktree paths the agent may touch.
	Worktrees []string
	// PathEnv is the PATH to export, so the agent can find its own tooling even
	// when the daemon was started with a minimal environment.
	PathEnv string
	// ExtraArgs are the user's configured arguments for this agent. They are
	// appended after everything q needs and before the prompt, so a user flag
	// cannot displace a flag the board depends on.
	ExtraArgs []string
	// CodexProfile is the codex profile q writes and selects. Empty means
	// DefaultCodexProfile.
	CodexProfile string
}

// Profile returns the codex profile name to select.
func (s LaunchSpec) Profile() string {
	if s.CodexProfile != "" {
		return s.CodexProfile
	}

	return DefaultCodexProfile
}

// extraArgs returns the user's configured arguments, shell-quoted.
func (s LaunchSpec) extraArgs() []string {
	out := make([]string, 0, len(s.ExtraArgs))
	for _, arg := range s.ExtraArgs {
		out = append(out, ShellQuote(arg))
	}

	return out
}

// Artifact returns the path of a generated file inside the mission directory.
func (s LaunchSpec) Artifact(name string) string {
	return filepath.Join(s.MissionDir, ArtifactDir, name)
}

// RenderLaunchScript generates the shell script that starts an agent.
//
// A script is generated rather than passing argv straight to tmux because tmux
// joins the trailing arguments of new-session and re-parses them through sh when
// they contain shell metacharacters. A composed prompt contains newlines, quotes,
// and backticks, so that path is unwinnable. Reading the prompt from a file
// sidesteps quoting entirely.
//
// The script is also the best debugging affordance in the tool: it can be run by
// hand to reproduce a launch exactly, and it is reused verbatim to relaunch.
//
// It ends in exec so the process replaces the shell. That is what makes tmux's
// pane_current_command report "claude" or "codex", which the guard on sending
// messages to a live session depends on, and it makes pane death mean agent death.
func RenderLaunchScript(spec LaunchSpec) (string, error) {
	args, err := AgentArgs(spec)
	if err != nil {
		return "", err
	}

	var b strings.Builder

	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by q. Safe to run by hand to reproduce this launch.\n")
	b.WriteString("set -eu\n")
	b.WriteString(`d="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"` + "\n")

	fmt.Fprintf(&b, "export %s=%s\n", EnvMissionID, ShellQuote(string(spec.MissionID)))
	fmt.Fprintf(&b, "export %s=%s\n", EnvHookEpoch, ShellQuote(fmt.Sprint(spec.HookEpoch)))
	fmt.Fprintf(&b, "export %s=%s\n", EnvDaemonFile, ShellQuote(spec.DaemonFile))

	if spec.PathEnv != "" {
		fmt.Fprintf(&b, "export PATH=%s\n", ShellQuote(spec.PathEnv))
	}

	if spec.Tool == domain.ToolCodex {
		writeCodexAppServerStart(&b, spec)
	}

	b.WriteString("\nexec ")
	b.WriteString(ShellQuote(spec.Bin))

	launchArgs := args
	if spec.Tool == domain.ToolCodex {
		launchArgs = codexDirectArgs(spec)
	}

	for _, arg := range launchArgs {
		b.WriteString(" \\\n  ")
		b.WriteString(arg)
	}

	b.WriteString("\n")

	return b.String(), nil
}

// writeCodexAppServerStart starts Codex's managed app-server and makes the
// terminal UI its client. The direct launch below remains the fallback for an
// older Codex release or a local app-server startup failure.
func writeCodexAppServerStart(b *strings.Builder, spec LaunchSpec) {
	b.WriteString("\nif ")
	b.WriteString(ShellQuote(spec.Bin))
	b.WriteString(" --profile ")
	b.WriteString(ShellQuote(spec.Profile()))
	b.WriteString(" app-server daemon start >/dev/null 2>&1; then\n")
	b.WriteString("  exec ")
	b.WriteString(ShellQuote(spec.Bin))

	for _, arg := range codexArgs(spec) {
		b.WriteString(" \\\n    ")
		b.WriteString(arg)
	}

	b.WriteString("\nfi\n")
}

// promptArg is the shell expression that substitutes the prompt file's contents.
//
// It is emitted unquoted on purpose: the command substitution must be evaluated,
// and the surrounding double quotes keep the result a single argument regardless of
// the newlines and spaces it contains.
const promptArg = `"$(cat "$d/` + PromptFile + `")"`

// AgentArgs builds the agent's arguments, already shell-quoted for the script.
//
// No variadic flag is ever emitted. claude's --add-dir accepts multiple values and
// would consume the positional prompt that follows it, so worktree access is
// granted through the settings file instead.
func AgentArgs(spec LaunchSpec) ([]string, error) {
	switch spec.Tool {
	case domain.ToolClaude:
		return claudeArgs(spec), nil
	case domain.ToolCodex:
		return codexArgs(spec), nil
	default:
		return nil, fmt.Errorf("unknown tool %q", spec.Tool)
	}
}

// claudeArgs builds claude's arguments.
func claudeArgs(spec LaunchSpec) []string {
	var args []string

	if spec.Resume && spec.SessionID != "" {
		args = append(args, "--resume", ShellQuote(spec.SessionID))
	} else if spec.SessionID != "" {
		// A session id chosen up front makes the session resumable from the
		// instant it starts, with no need for the agent to report it back.
		args = append(args, "--session-id", ShellQuote(spec.SessionID))
	}

	if spec.DisplayName != "" {
		args = append(args, "--name", ShellQuote(spec.DisplayName))
	}

	mode := "auto"
	if spec.PlanMode {
		mode = "plan"
	}

	args = append(args, "--permission-mode", mode)
	args = append(args, "--settings", `"$d/`+ClaudeSettingsFile+`"`)
	args = append(args, spec.extraArgs()...)

	return append(args, promptArg)
}

// codexArgs builds codex's arguments.
//
// The user's approval policy and sandbox mode are deliberately left alone: no -s, no
// -a, and no bypass flag of any kind. Everything q needs to configure travels in
// the profile, which is also where directory trust lives because codex will not accept
// it on the command line.
func codexArgs(spec LaunchSpec) []string {
	args := codexDirectArgs(spec)

	// The empty Unix URL selects Codex's managed app-server control socket.
	// Keeping the transport local avoids a TCP listener and any credential.
	insertAt := 0
	if spec.Resume && spec.SessionID != "" {
		insertAt = 1
	}

	remote := []string{"--remote", "unix://"}
	args = append(args, remote...)
	copy(args[insertAt+len(remote):], args[insertAt:len(args)-len(remote)])
	copy(args[insertAt:], remote)

	return args
}

// codexDirectArgs is the compatibility invocation used when app-server is not
// available. It intentionally remains equivalent to the pre-integration argv.
func codexDirectArgs(spec LaunchSpec) []string {
	if spec.Resume && spec.SessionID != "" {
		return codexResumeArgs(spec)
	}

	args := codexCommonArgs(spec)

	for _, wt := range spec.Worktrees {
		args = append(args, "--add-dir", ShellQuote(wt))
	}

	return append(args, promptArg)
}

// codexCommonArgs are the flags shared by a fresh launch and a resume.
//
// The mission directory is written out in full rather than as "$d/..": codex matches
// project trust on the exact path it is given, so an unresolved path containing ".."
// would not match the trust entry written for it.
//
// Trust itself is not passed here. codex ignores it as a -c override and reads it from
// a config file only, so it lives in the profile instead.
func codexCommonArgs(spec LaunchSpec) []string {
	return append([]string{
		"--cd", ShellQuote(spec.MissionDir),
		"--profile", ShellQuote(spec.Profile()),
	}, spec.extraArgs()...)
}

// codexResumeArgs resumes a codex session by id.
//
// codex has no --session-id, so the id here was learned from the session's own
// SessionStart hook. When it is unknown, callers fall back to `codex resume --last`
// run from the mission directory, which works only because codex filters resume
// candidates by working directory and mission directories are unique per mission.
func codexResumeArgs(spec LaunchSpec) []string {
	// The subcommand leads; its flags follow it.
	args := append([]string{"resume"}, codexCommonArgs(spec)...)
	args = append(args, ShellQuote(spec.SessionID))

	return append(args, promptArg)
}
