package mission

import (
	"context"
	"os"
)

// Agent is one coding agent q can run a mission with.
//
// Everything that differs between claude, codex, and whatever comes next is
// reached through this interface, so adding an agent is a new package rather
// than a new branch in each of these files. Implementations live in
// internal/claude and internal/codex; the cmd package builds them from the
// user's configuration and hands them to a [Service].
//
// An implementation runs no processes and touches no state: it is a pure
// function from an [Invocation] to argv and bytes, which is what lets a whole
// launch be asserted in tests without an agent installed.
type Agent interface {
	// Tool reports which agent this is.
	Tool() Tool
	// Bin is the absolute path to the agent's executable.
	Bin() string
	// Args returns the agent's arguments, already shell-quoted for the launch
	// script.
	Args(Invocation) []string
	// Prologue is shell emitted before the script's final exec, for an agent that
	// needs an environment variable exported, a sidecar started, or a preferred
	// invocation tried first. Most agents return "".
	Prologue(Invocation) string
	// Artifacts are the files the agent needs written before it starts.
	Artifacts(Invocation) ([]Artifact, error)
	// HookEvents lists the hook events the agent is configured to report.
	HookEvents() []string
}

// Invocation is everything an agent needs to know to run one mission.
type Invocation struct {
	// MissionID and HookEpoch identify the mission to its hooks.
	MissionID MissionID
	HookEpoch int
	// MissionDir is the agent's working directory.
	MissionDir string
	// MissionDirs are every mission directory currently on disk, including this
	// one. An agent that must be told which directories it may trust in advance
	// needs the whole set, not just its own.
	MissionDirs []string
	// DaemonFile is the path to the daemon handle.
	DaemonFile string
	// SessionID is the agent session to use or resume. For an agent that accepts
	// a preset id this is chosen in advance; otherwise it is only known after the
	// session has started, and so is empty on a first launch.
	SessionID string
	// Resume continues SessionID rather than starting fresh.
	Resume bool
	// PlanMode starts the agent in a plan-then-approve flow, for an agent that
	// supports one.
	PlanMode bool
	// DisplayName is shown in the agent's own UI.
	DisplayName string
	// Worktrees are the absolute worktree paths the agent may touch.
	Worktrees []string
	// PathEnv is the PATH to export, so the agent can find its own tooling even
	// when the daemon was started with a minimal environment.
	PathEnv string
	// QBin is the absolute path to the q binary, embedded in hook commands.
	QBin string
}

// Artifact is a file an agent needs written before it starts.
type Artifact struct {
	// Path names the file. A relative path is resolved inside the mission's
	// artifact directory; an absolute path is written as given, which is how an
	// agent configured from its own home directory is served.
	Path string
	// Data is the file's contents.
	Data []byte
	// Mode is the file's permissions.
	Mode os.FileMode
	// Merge, when set, combines the generated bytes with what is already on disk
	// and reports whether anything needs writing. It exists for a file an agent
	// writes to as well as reads, such as a profile carrying hook approvals that
	// must survive regeneration.
	Merge func(generated, existing []byte) ([]byte, bool)
}

// Activity is what an agent's own runtime says a session is doing.
type Activity string

// The activities an agent runtime can report.
const (
	ActivityUnknown         Activity = ""
	ActivityBusy            Activity = "busy"
	ActivityWaitingApproval Activity = "waiting_approval"
	ActivityWaitingInput    Activity = "waiting_input"
	ActivityIdle            Activity = "idle"
	ActivityFailed          Activity = "failed"
)

// Reading is one observation of a live agent session.
type Reading struct {
	// SessionID is the agent's own identifier for the session observed.
	SessionID string
	// PaneID is the tmux pane the session occupies, when the agent knows it.
	// An agent that reports this beats anything q inferred.
	PaneID string
	// Activity is what the session is doing.
	Activity Activity
	// WaitingFor describes what a waiting session is blocked on.
	WaitingFor string
}

// Runtime reports process truth from an agent's own runtime.
//
// A Runtime is authoritative: q polls it and its readings move a card in either
// direction, because it observes the running process rather than inferring from
// events that may have been missed.
type Runtime interface {
	Read(ctx context.Context, ms Mission) (Reading, bool, error)
	Close() error
}

// Healer reports what an agent's own session registry says.
//
// A Healer is advisory. Its readings only correct a card that a dropped hook
// left wrong, and each rule is deliberately conservative about the direction it
// moves one, because the registry is a best-effort signal and hooks remain q's
// primary source.
type Healer interface {
	Heal(ctx context.Context, missions []Mission) (map[MissionID]Reading, error)
}
