// Package opencode runs missions with OpenCode's terminal CLI.
package opencode

import (
	"encoding/json"
	"fmt"
	"path/filepath"

	"github.com/justinrush/q/internal/mission"
)

// Options configure an [Agent].
type Options struct {
	// Args are extra arguments appended to every invocation, before the prompt.
	Args []string
}

// Agent runs missions with opencode.
type Agent struct {
	bin  string
	args []string
}

// New returns an agent invoking the opencode binary at bin.
func New(bin string, opts Options) *Agent {
	return &Agent{bin: bin, args: opts.Args}
}

// Tool reports that this is the opencode agent.
func (*Agent) Tool() mission.Tool { return mission.ToolOpencode }

// Bin is the absolute path to the opencode executable.
func (a *Agent) Bin() string { return a.bin }

// Prologue needs no environment exports for opencode.
func (*Agent) Prologue(mission.Invocation) string { return "" }

// HookEvents returns the events q subscribes to via the opencode plugin.
func (*Agent) HookEvents() []string {
	return []string{
		mission.EventSessionStart,
		mission.EventSessionEnd,
		mission.EventUserPromptSubmit,
		mission.EventPreToolUse,
		mission.EventPostToolUse,
		mission.EventPermissionRequest,
		mission.EventStop,
		mission.EventStopFailure,
	}
}

// Args builds opencode's arguments.
func (a *Agent) Args(inv mission.Invocation) []string {
	var args []string

	if inv.Resume && inv.SessionID != "" {
		args = append(args, "--session", mission.ShellQuote(inv.SessionID))
	}

	if inv.PlanMode {
		args = append(args, "--agent", "plan")
	}

	if inv.Model != "" {
		args = append(args, "--model", mission.ShellQuote(inv.Model))
	}

	args = append(args, mission.ShellQuoteAll(a.args)...)

	return append(args, "--prompt", mission.PromptArg)
}

// Artifacts generates opencode.json and the q-status plugin in the mission's .opencode directory.
func (a *Agent) Artifacts(inv mission.Invocation) ([]mission.Artifact, error) {
	configData, err := renderConfig(inv)
	if err != nil {
		return nil, fmt.Errorf("rendering opencode config: %w", err)
	}

	configArtifact := mission.Artifact{
		Path: filepath.Join(inv.MissionDir, ".opencode", "opencode.json"),
		Data: configData,
		Merge: func(generated, existing []byte) ([]byte, bool) {
			return mergeConfig(inv, generated, existing)
		},
	}

	pluginData := renderPlugin(inv)
	pluginArtifact := mission.Artifact{
		Path: filepath.Join(inv.MissionDir, ".opencode", "plugins", "q-status.js"),
		Data: pluginData,
	}

	return []mission.Artifact{configArtifact, pluginArtifact}, nil
}

func renderConfig(inv mission.Invocation) ([]byte, error) {
	doc := map[string]any{
		"$schema": "https://opencode.ai/config.json",
		"permission": map[string]any{
			"external_directory": "allow",
		},
	}

	if inv.Model != "" {
		doc["model"] = inv.Model
	}

	if inv.Effort != "" {
		doc["agent"] = map[string]any{
			"build": map[string]any{"variant": inv.Effort},
			"plan":  map[string]any{"variant": inv.Effort},
		}
	}

	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, err
	}

	return append(data, '\n'), nil
}

func mergeConfig(inv mission.Invocation, generated, existing []byte) ([]byte, bool) {
	if len(existing) == 0 {
		return generated, true
	}

	var root map[string]any
	if err := json.Unmarshal(existing, &root); err != nil || root == nil {
		return existing, false
	}

	perm, ok := root["permission"].(map[string]any)
	if !ok || perm == nil {
		perm = map[string]any{}
	}
	perm["external_directory"] = "allow"
	root["permission"] = perm

	if inv.Model != "" {
		root["model"] = inv.Model
	}

	if inv.Effort != "" {
		agent, ok := root["agent"].(map[string]any)
		if !ok || agent == nil {
			agent = map[string]any{}
		}
		buildAgent, ok := agent["build"].(map[string]any)
		if !ok || buildAgent == nil {
			buildAgent = map[string]any{}
		}
		buildAgent["variant"] = inv.Effort
		agent["build"] = buildAgent

		planAgent, ok := agent["plan"].(map[string]any)
		if !ok || planAgent == nil {
			planAgent = map[string]any{}
		}
		planAgent["variant"] = inv.Effort
		agent["plan"] = planAgent

		root["agent"] = agent
	}

	data, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return existing, false
	}

	return append(data, '\n'), true
}

func renderPlugin(inv mission.Invocation) []byte {
	script := fmt.Sprintf(`// Generated by q. Reports OpenCode events to the q daemon.
import { spawn } from 'node:child_process';

export const QStatus = async () => {
  const qBin = process.env.Q_BIN || %q;
  const seenUserMsgs = new Set();

  const send = (event, payload) => {
    try {
      const child = spawn(qBin, ['hook', 'opencode', event], {
        stdio: ['pipe', 'ignore', 'ignore'],
        env: process.env,
      });
      child.on('error', () => {});
      child.stdin.write(JSON.stringify(payload || {}));
      child.stdin.end();
      if (child.unref) {
        child.unref();
      }
    } catch (e) {}
  };

  return {
    event: async (input) => {
      const ev = input && input.event;
      if (!ev || !ev.type) return;
      const p = ev.properties || {};
      const info = p.info || {};
      const sessionID = info.id || p.sessionID || p.id || '';

      switch (ev.type) {
        case 'session.created':
          send('session-start', {
            session_id: sessionID,
            cwd: info.directory || p.directory || process.cwd(),
            source: 'startup',
          });
          break;
        case 'session.deleted':
          send('session-end', { session_id: sessionID });
          break;
        case 'session.idle':
          send('stop', { session_id: sessionID });
          break;
        case 'session.error': {
          const errReason = (p.error && (p.error.message || p.error.name)) || 'session error';
          send('stop-failure', { session_id: sessionID, reason: errReason });
          break;
        }
        case 'permission.updated':
          send('permission-request', {
            session_id: sessionID,
            tool_name: p.type || 'permission',
          });
          break;
        case 'permission.replied':
          send('post-tool-use', {
            session_id: sessionID,
            tool_name: p.type || '',
          });
          break;
        case 'question.asked':
          send('permission-request', {
            session_id: (p.data && p.data.sessionID) || sessionID,
            tool_name: 'question',
          });
          break;
        case 'question.replied':
        case 'question.rejected':
          send('post-tool-use', {
            session_id: (p.data && p.data.sessionID) || sessionID,
            tool_name: 'question',
          });
          break;
        case 'message.updated':
          if ((info.role || p.role) !== 'user') return;
          if (info.id) {
            if (seenUserMsgs.has(info.id)) return;
            seenUserMsgs.add(info.id);
            if (seenUserMsgs.size > 500) {
              for (const first of seenUserMsgs) {
                seenUserMsgs.delete(first);
                break;
              }
            }
          }
          send('user-prompt-submit', {
            session_id: info.sessionID || sessionID,
            prompt: '',
          });
          break;
      }
    },
    'tool.execute.before': async (input) => {
      if (!input) return;
      send('pre-tool-use', {
        session_id: input.sessionID || '',
        tool_name: input.tool || '',
      });
    },
    'tool.execute.after': async (input) => {
      if (!input) return;
      send('post-tool-use', {
        session_id: input.sessionID || '',
        tool_name: input.tool || '',
      });
    },
  };
};
`, inv.QBin)

	return []byte(script)
}
